services:
  payload:
    container_name: payload
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./docker/prod:/home/node/app/src/media
    ports:
      - 3006:3002
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:16
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - sms_database:/var/lib/postgresql/data

volumes:
  sms_database:
