services:
  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
    restart: unless-stopped

  payload:
    container_name: payload
    image: ghcr.io/dhzdhd/opensms:latest
    env_file:
      - .env
    volumes:
      - ./media:/home/node/app/src/media
    depends_on:
      - database
      - swag
    restart: unless-stopped

  database:
    container_name: database
    image: postgres:16
    env_file:
      - .env
    volumes:
      - sms_database:/var/lib/postgresql/data
    restart: unless-stopped

  backups:
    container_name: backups
    image: prodrigestivill/postgres-backup-local
    user: postgres:postgres
    volumes:
      - /var/opt/backups:/backups
    links:
      - database
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    restart: unless-stopped

volumes:
  sms_database:
