services:
  payload:
    container_name: payload
    image: ghcr.io/dhzdhd/opensms:latest
    env_file:
      - .env
    volumes:
      - ./media:/home/node/app/src/media
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:16
    env_file:
      - .env
    volumes:
      - sms_database:/var/lib/postgresql/data

volumes:
  sms_database:
