---
- name: Setup Docker
  hosts: cloud
  become: true
  tasks:
    - name: Update
      ansible.builtin.apt:
        update_cache: true

    - name: Install prerequisite packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Start docker on boot
      ansible.builtin.systemd:
        name: docker.service
        enabled: true

    - name: Start containerd on boot
      ansible.builtin.systemd:
        name: containerd.service
        enabled: true
