name: Build and release Tauri desktop app

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: frontend
        sparse-checkout-cone-mode: false

    - name: Move frontend files to root (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        Get-ChildItem -Force -File | Format-List
        Move-Item -Path 'frontend\*' -Destination .
        Remove-Item -Recurse -Force -Path 'frontend'
        Get-ChildItem -Force -File | Format-List

    - name: Move frontend files to root (Unix)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        ls -lah
        shopt -s dotglob
        mv frontend/* .
        rm -rf frontend
        ls -lah

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Enable corepack for yarn
      run: corepack enable

    - name: Setup rust
      run: rustup toolchain install stable

    - name: Setup rust targets
      run: rustup target add x86_64-pc-windows-msvc

    - name: Install site packages
      run: yarn install

    - name: Build app
      run: yarn run tauri build

    - name: Debug target folder
      run: tree src-tauri/target

    - name: Save package
      uses: actions/upload-artifact@v4
      with:
        # Do not use wildcard because directory structure is preserved
        if-no-files-found: warn
        path: |
          src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*
          src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*

  release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get all build outputs
        uses: actions/download-artifact@v3
        with:
          path: outputs

      - name: Debug outputs folder
        run: tree outputs

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: OpenSMS
          body_path: CHANGELOG.txt
          repository: dhzdhd/OpenSMS
          prerelease: true
          generate_release_notes: true
          files: outputs/*
          token: ${{ secrets.GITHUB_TOKEN }}
